server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  #filename: /etc/promtail/config/positions.yaml
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
target_config:
  sync_period: 10s
scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
  - job_name: var-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: dpkg-logs
          application: system
          env: dev
          __path__: /var/log/dpkg.log
      - targets:
          - localhost
        labels:
          job: auth-logs
          application: system
          env: dev
          __path__: /var/log/auth.log
      - targets:
          - localhost
        labels:
          job: kern-logs
          application: system
          env: dev
          __path__: /var/log/kern.log
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: address
