server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/config/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    headers:
      - X-Scope-OrgID: monitoring

target_config:
  sync_period: 10s

scrape_configs:
  - job_name: var-log
    static_configs:
      - targets:
          - localhost
        labels:
          application: ubuntu
          env: dev
          __path__: /var/log/*.log
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: address